---
- raw: dnf install -y python2 python2-dnf libselinux-python
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22
  
- name: install required dnf packages
  dnf: name={{ item }} state=installed
  with_items:
    - firewalld
    - firewall-config
    - python2-pexpect
    - python-firewall
    - dkms 
    - kernel-headers 
    - kernel 
    - kernel-devel 
    - gcc 
    - make
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22
        
- name: install required yum packages
  yum: name={{ item }} state=installed
  with_items:
    - firewalld
    - firewall-config
    - python2-pexpect
    - python-firewall
    - dkms 
    - kernel-headers 
    - kernel 
    - kernel-devel 
    - gcc 
    - make
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 7

- name: adding virtualbox repository
  template: src=redhat_virtualbox.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 7
  
- name: adding virtualbox repository
  template: src=fedora_virtualbox.repo.j2 dest=/etc/yum.repos.d/virtualbox.repo
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22
  
- name: install virtualbox with dnf
  dnf: name=VirtualBox-5.0 state=latest 
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22
  
- name: install virtualbox with yum
  yum: name=VirtualBox-5.0 state=latest 
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 7

- name: copy vagrant rpm to /tmp
  copy: src=files/vagrant_1.8.6_x86_64.rpm dest=/tmp/vagrant.rpm


- name: install vagrant with dnf
  dnf: name=/tmp/vagrant.rpm state=present
  changed_when: false
  when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22

- name: install vagrant with yum
  yum: name=/tmp/vagrant.rpm state=present
  changed_when: false
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 7


- name: Open up firewalld for nfs
  firewalld: service={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Open up firewalld for devnet ports
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - 2049/udp
    
- name: Install system group
  group: name=vagrant state=present

- name: write sudoers.d
  template: src=sudoers.j2 dest=/etc/sudoers.d/vagrant mode=0755 validate='visudo -cf %s'

