---
- include: setup-RedHat.yml
  when: ansible_distribution == 'RedHat'

- include: setup-Fedora.yml
  when: ansible_distribution == 'Fedora'

- name: Open up firewalld for nfs service
  firewalld: service={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - nfs
    - rpc-bind
    - mountd

- name: Open up firewalld ports for nfs
  firewalld: port={{ item }} permanent=true state=enabled immediate=true
  with_items:
    - 2049/udp
    
- name: Install system group
  group: name=vagrant state=present

- name: write sudoers.d
  template: src=sudoers.j2 dest=/etc/sudoers.d/vagrant mode=0755 validate='visudo -cf %s'

